services:
  - type: web
    name: like-ff-app
    runtime: python
    buildCommand: ""
    startCommand: python app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
    autoDeploy: true
    plan: free